name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-14, windows-2022, ubuntu-22.04]
        include:
          - os: macos-12
            target: x86_64-apple-darwin
          - os: macos-14
            target: aarch64-apple-darwin
          - os: windows-2022
            target: x86_64-pc-windows-msvc
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux deps
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update -y
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \\
            libasound2-dev \\
            libx11-dev \\
            libxi-dev \\
            libxrandr-dev \\
            libxcursor-dev \\
            libxkbcommon-dev \\
            libwayland-dev \\
            libxinerama-dev \\
            libudev-dev \\
            libegl1-mesa-dev \\
            libgl1-mesa-dev \\
            libx11-xcb-dev \\
            libxcb-render0-dev \\
            libxcb-shape0-dev \\
            libxcb-xfixes0-dev \\
            pkg-config

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
